### ISSUE TITLE
Provide option to not detect reaction_remove events

### ISSUE THREAD

**Issue by Chiggy-Playz** [Rapptz/discord-ext-menus#43] opened 2021-06-06 19:04 UTC
Maybe there can be a boolean argument provided to init of menu, telling the menu to whether accept reaction_remove or not. This can solve the issue of removal of the reaction of the user by the bot, since the bot isnt listening to the reaction_remove event. By default, the boolean can be True, meaning that the menu will observe reaction_remove event.  I can open a PR if needed too

**Comment by Rapptz** [comment] 2021-06-06 19:06
Duplicate of https://github.com/Rapptz/discord-ext-menus/pull/35 https://github.com/Rapptz/discord-ext-menus/pull/36 and https://github.com/Rapptz/discord-ext-menus/pull/19

**Closed as completed by Rapptz** 2021-06-06 19:06 UTC
